[tool.poetry]
name = "amdb-backend"
version = "0.1.0"
description = "Awesome Movie Database backend"
authors = ["Madnoberson"]
readme = "README.md"
packages = [{include = "src/"}]
license = "Apache"

[tool.poetry.dependencies]
python = "^3.10"
sqlalchemy = "^2.0.23"
alembic = "^1.13.0"
psycopg2-binary = "^2.9.9"

[tool.poetry.group.dev.dependencies]
mypy = "^1.7.0"
ruff = "^0.1.6"
pre-commit = "^3.5.0"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"
coverage = "^7.3.2"
pytest-cov = "^4.1.0"
pytest-clarity = "^1.0.1"
polyfactory = "^2.13.0"

[tool.pytest.ini_options]
pythonpath = "src/"
python_functions = "when_* test_*"

[tool.ruff]
line-length = 99

[tool.ruff.lint]
extend-select = [
    "N",
    "EM",
    "ISC",
    "G",
    "Q",
]
select = [
    "F401",
    "F406",
    "COM812",
    "DTZ003",
    "EM102",
    "INP001",
    "PIE794",
    "PIE796",
    "T201",
    "SLF001",
]
ignore = [
    "N999",
]

[tool.ruff.format]
quote-style = "double"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
