[tool.poetry]
name = "amdb-backend"
version = "0.1.0"   
description = "Awesome Movie Database backend"
authors = ["Madnoberson"]
readme = "README.md"
license = "Apache"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
mypy = "^1.7.0"
ruff = "^0.1.6"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.3"

[tool.ruff]
line-length = 99

[tool.ruff.lint]
extend-select = [
    "N",
    "EM",
    "ISC",
    "G",
    "Q",
]
select = [
    "F401",
    "F406",
    "COM812",
    "DTZ003",
    "EM102",
    "INP001",
    "PIE794",
    "PIE796",
    "T201",
    "SLF001",
]

[tool.ruff.format]
quote-style = "double"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
