[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Awesome Movie Database Backend"
description = "Movie Database"
readme = "README.md"
requires-python = ">=3.10"
license = "Apache"
