"""Create User and Profile tables

Revision ID: fe0cbb8173cb
Revises:
Create Date: 2023-12-15 20:43:36.904402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe0cbb8173cb"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("sex", sa.Integer(), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("verified_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("achievements", sa.Integer(), nullable=False),
        sa.Column("movie_ratings", sa.Integer(), nullable=False),
        sa.Column("series_episode_ratings", sa.Integer(), nullable=False),
        sa.Column("approved_reviews", sa.Integer(), nullable=False),
        sa.Column("movie_reviews", sa.Integer(), nullable=False),
        sa.Column("series_reviews", sa.Integer(), nullable=False),
        sa.Column("series_season_reviews", sa.Integer(), nullable=False),
        sa.Column("series_episode_reviews", sa.Integer(), nullable=False),
        sa.Column("given_votes", sa.Integer(), nullable=False),
        sa.Column("gained_votes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profiles")
    op.drop_table("users")
    # ### end Alembic commands ###
