LOGIN_ACCESS_DENIED = "Access to login in denied"
GET_MOVIES_ACCESS_DENIED = "Access to getting movies is denied"
GET_MOVIE_ACCESS_DENIED = "Access to getting movie is denied"
CREATE_MOVIE_ACCESS_DENIED = "Access to movie creation is denied"
DELETE_MOVIE_ACCESS_DENIED = "Access to movie deletion is denied"
GET_RATING_ACCESS_DENIED = "Access to getting movie rating is denied"
RATE_MOVIE_ACCESS_DENIED = "Access to movie rating is denied"
UNRATE_MOVIE_ACCESS_DENIED = "Access to movie unrating is denied"
REVIEW_MOVIE_ACCESS_DENIED = "Access to movie reviewing is denied"

USER_NAME_ALREADY_EXISTS = "User name already exists"
USER_DOES_NOT_EXIST = "User doesn't exist"
INCORRECT_PASSWORD = "Password is not correct"

MOVIE_DOES_NOT_EXIST = "Movie doesn't exist"
MOVIE_ALREADY_RATED = "Movie is already rated"
MOVIE_NOT_RATED = "Movie is not rated"
MOVIE_ALREADY_REVIEWED = "Review is already reviewed"
