name: lint
run-name: linting

on:
  push:
    branches: [main]
    paths: ["src/**", "tests/**"]
  pull_request:
    types: [opened]
    paths: ["src/**", "tests/**"]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install python3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install dependencies
        run: pipx install poetry && poetry install
      - name: run format
        run: poetry run ./scripts/format.sh
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install python3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install dependencies
        run: pipx install poetry && poetry install
      - name: run lint
        run: poetry run ./scripts/lint.sh
