name: lint
run-name: linting

on:
  push:
    branches: [main]
    paths: ["src/**", "tests/**"]
  pull_request:
    types: [opened]
    paths: ["src/**", "tests/**"]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install python3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.13"
      - name: install dependencies
        run: pip install ".[style]"
      - name: run format
        run: ./scripts/format.sh
  lint:
    needs: [format]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install python3.10.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.13"
      - name: install dependencies
        run: pip install ".[style]"
      - name: run lint
        run: ./scripts/lint.sh
