name: test
run-name: testing

on:
  push:
    branches: [main]
    paths: ["*.py"]
  pull_request:
    types: [opened]
    paths: ["*.py"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install python3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install dependencies
        run: pipx install poetry && poetry install
      - name: run test
        run: poetry run ./scripts/test.sh
